name: Build and Push Image
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write   # keyless 서명용
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/step10-cicd

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        id: push
        with:
          context: ./step10-CICD
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.run_number }}
            ${{ env.IMAGE }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TEAM=chathongpt
            COLOR=${{ secrets.TEAM_COLOR }}

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.IMAGE }}@${{ steps.push.outputs.digest }}"
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: 1

      - name: Generate SBOM with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.IMAGE }}@${{ steps.push.outputs.digest }}"
          scan-type: "image"
          format: "cyclonedx"
          output: "sbom.json"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Container Image
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          cosign sign --yes \
            ${{ env.IMAGE }}@${DIGEST}

      - name: Attest SBOM
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          ls -la
          echo "IMAGE=${{ env.IMAGE }} DIGEST=${DIGEST}"
          cosign attest --yes --predicate sbom.json --type cyclonedx "${{ env.IMAGE }}@${DIGEST}"
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 113.198.66.75
          username: ubuntu
          port: 19193 
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 10m
          script: |
            OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
            IMAGE="ghcr.io/${OWNER_LC}/application"
            docker login ghcr.io -u '${{ github.actor }}' -p '${{ secrets.G_TOKEN }}'
            docker pull "${IMAGE}:sha-${{ github.sha }}"
            docker rm -f app || true
            docker run -d --name app -p 8080:8080 "${IMAGE}:sha-${{ github.sha }}"
