name: Build and Push Image
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # keyless 서명용
      packages: write   # GHCR push 권한
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/step10-cicd

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        id: push
        with:
          context: ./step10-CICD
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.run_number }}
            ${{ env.IMAGE }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TEAM=chathongpt
            COLOR=${{ secrets.TEAM_COLOR }}

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.IMAGE }}@${{ steps.push.outputs.digest }}"
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: 1

      - name: Generate SBOM with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.IMAGE }}@${{ steps.push.outputs.digest }}"
          scan-type: "image"
          format: "cyclonedx"
          output: "sbom.json"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Container Image
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          cosign sign --yes \
            ${{ env.IMAGE }}@${DIGEST}

      - name: Attest SBOM
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          cosign attest --yes \
            --predicate sbom.json \
            --type cyclonedx \
